### ISSUE TITLE
I can not see this file please

### ISSUE THREAD

**Issue by benyaadeyanju** [subha996/OD-yolov5_1#1]
\mylogs\\infer.log'

**Comment by benyaadeyanju** [comment]
I tried to follow your instruction but when i ran 
streamlit run st.py

errors

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Asus99\\Desktop\\Test_video\\OD-yolov5_1\\mylogs\\infer.log' ( my folder name-- 'C:\\Users\\Asus99\\Desktop\\Test_video\)

**Comment by subha996** [comment]
hi [benyaadeyanju](https://github.com/benyaadeyanju),
you can solve the error by creating an empty directory(folder) named `mylogs` manually on your working directory. there a logfile will be generate called `infer.log` and make sure you have installed all the necessary libraries.

**Comment by subha996** [comment]
closing the issue due to inactivity.
